version: '3'
services:
  discord_bot:
    image: ghcr.io/k-velorum/thumbnailer_discord_docker:latest
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    volumes:
      - ./src:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
